---
# Source: questdb/templates/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-questdb
  labels:
    helm.sh/chart: questdb-0.18.0
    app.kubernetes.io/name: questdb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "6.2.1"
    app.kubernetes.io/managed-by: Helm
data:
  server.conf: |
    shared.worker.count = 2
---
# Source: questdb/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-questdb-headless
  labels:
    helm.sh/chart: questdb-0.18.0
    app.kubernetes.io/name: questdb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "6.2.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 8812
      targetPort: postgresql
  selector:
    app.kubernetes.io/name: questdb
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: questdb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-questdb
  labels:
    helm.sh/chart: questdb-0.18.0
    app.kubernetes.io/name: questdb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "6.2.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: questdb
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: questdb/templates/stateful-set.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: RELEASE-NAME-questdb
  labels:
    helm.sh/chart: questdb-0.18.0
    app.kubernetes.io/name: questdb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "6.2.1"
    app.kubernetes.io/managed-by: Helm
spec:
  # Not horizontally scalable yet, so pinning to 1
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: questdb
      app.kubernetes.io/instance: RELEASE-NAME
  serviceName: "RELEASE-NAME-questdb-headless"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: questdb
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      securityContext:
        {}
      containers:
        - name: questdb
          securityContext:
            {}
          image: "questdb/questdb:6.2.1"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: RELEASE-NAME-questdb
            mountPath: /root/.questdb/db
          - name: config
            mountPath: /root/.questdb/conf/server.conf
            subPath: server.conf

          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: postgresql
              containerPort: 8812
              protocol: TCP
            - name: influxdb
              containerPort: 9009
              protocol: TCP
          # QuestDB doesn't really expose an endpoint that works well for
          # these probes. Hopefully soon?
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {}
      volumes:
        - name: config
          configMap:
            name: RELEASE-NAME-questdb

  volumeClaimTemplates:
    - metadata:
        name: RELEASE-NAME-questdb
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "50Gi"
---
# Source: questdb/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "RELEASE-NAME-questdb-test-connection"
  labels:
    helm.sh/chart: questdb-0.18.0
    app.kubernetes.io/name: questdb
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "6.2.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: curl
      image: curlimages/curl:7.71.0
      command: ['curl']
      args: ['-G', 'RELEASE-NAME-questdb:9000', '--data-urlencode', 'query="SHOW TABLES;"']
  restartPolicy: Never
